parameters:
- name: image
  displayName: Pool Image
  values:
  - windows-latest
  - ubuntu-latest
  - macOS-latest
- name: test
  displayName: Run Tests?
  type: boolean
  default: false
  
resources:
  repositories:
  - repository: MVCwithDocket # The name used to reference this repository in the checkout step
    type: github
    endpoint: Vigneshwar-Meganathan
    name: Vigneshwar-Meganathan/MVCwithDocket
    trigger:
    - master

trigger:
- main

pool:
  vmImage: 'windows-latest'


steps:
- checkout: self
- checkout: MVCwithDocket

- script: dir $(Build.SourcesDirectory)
- script: ls $(Build.SourcesDirectory)/MVCProject
- script: ls $(Build.SourcesDirectory)/MVCwithDocket

