parameters:
- name: image
  displayName: Pool Image
  values:
  - windows-latest
  - ubuntu-latest
  - macOS-latest
- name: MVCProj
  displayName: MVCProject
  type: boolean
  default: false
- name: MVCwithDock
  displayName: MVCwithDocket
  type: boolean
  default: false

resources:
  repositories:
  - repository: MVCwithDocket # The name used to reference this repository in the checkout step
    type: github
    endpoint: Vigneshwar-Meganathan
    name: Vigneshwar-Meganathan/MVCwithDocket
    trigger: none
 
trigger:
- none

steps:
- ${{ if eq(parameters.MVCProj, true) }}:
    - script: echo "Checkout the MVCProject"
- script: ls $(Build.SourcesDirectory)/MVCProject
- checkout: self
- script: dir $(Build.SourcesDirectory)

- ${{ if eq(parameters.MVCwithDock, true) }}:
    - script: echo "Checkout the MVCwithDocker"
- script: ls $(Build.SourcesDirectory)/MVCwithDocket
- checkout: MVCwithDocket
- script: dir $(Build.SourcesDirectory)


