parameters:
- name: image
  displayName: Pool Image
  values:
  - windows-latest
  - ubuntu-latest
  - macOS-latest
  default: ubuntu-latest

- name: MVCProj
  displayName: MVCProject
  type: boolean
  default: false
  
- name: MVCwithDock
  displayName: MVCwithDocket
  type: boolean
  default: false

resources:
  repositories:
  - repository: MVCwithDocket # The name used to reference this repository in the checkout step
    type: github
    endpoint: Vigneshwar-Meganathan
    name: Vigneshwar-Meganathan/MVCwithDocket
     

steps:
- ${{ if eq(parameters.MVCProj, true) }}:
    - script: echo "Checkout the MVCProject"
- checkout: self
- script: ls $(Build.SourcesDirectory)/MVCProject
- script: dir $(Build.SourcesDirectory)

- ${{ if eq(parameters.MVCwithDock, true) }}:
    - script: echo "Checkout the MVCwithDocker"
- checkout: MVCwithDocket
- script: ls $(Build.SourcesDirectory)/MVCwithDocket
- script: dir $(Build.SourcesDirectory)


