resources:
  repositories:
  - repository: MVCwithDocket # The name used to reference this repository in the checkout step
    type: github
    endpoint: Vigneshwar-Meganathan
    name: Vigneshwar-Meganathan/MVCwithDocket
    trigger:
    - master

trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self
- checkout: MVCwithDocket

- script: dir $(Build.SourcesDirectory)

- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 4.4.1'
  inputs:
    versionSpec: 4.4.1

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: '$(Parameters.solution)'

